
@baseurl= http://localhost:4000/
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInVzZXJuYW1lIjoiY29iYSIsInJvbGUiOiJlZGl0b3IiLCJtZW51cyI6WyIvZGFzaGJvYXJkIiwiL3Bvc3RzL2NyZWF0ZSIsIi9wb3N0cyJdLCJpYXQiOjE3NzIzMzQyMTcsImV4cCI6MTc3MjM0MTQxN30.gYTd6w_2VPrpAzYsOAunsvmrucWdFhQc-4OhmMQeKlc
@refreshtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInVzZXJuYW1lIjoiY29iYSIsInJvbGUiOiJlZGl0b3IiLCJtZW51cyI6WyIvZGFzaGJvYXJkIiwiL3Bvc3RzL2NyZWF0ZSIsIi9wb3N0cyJdLCJpYXQiOjE3NzE3MzcwMjAsImV4cCI6MTc3MTgyMzQyMH0.I46dxxwkHUfa5zTnMub-9WzFiH1WrNjCrZozV03FCjk
### login
POST {{baseurl}}auth/login
Content-Type: application/json

{
  "username": "coba",
  "password": "password123"
} 

### refresh token
POST {{baseurl}}auth/refresh
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 8,
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInVzZXJuYW1lIjoiY29iYSIsInJvbGUiOiJlZGl0b3IiLCJtZW51cyI6WyIvZGFzaGJvYXJkIiwiL3Bvc3RzL2NyZWF0ZSIsIi9wb3N0cyJdLCJpYXQiOjE3NzE3MzcyNTQsImV4cCI6MTc3MTgyMzY1NH0.orWmXf1ahmRgLTdQfMYyt66GNeZo0GF2aAZGKWeXMIA"
}


### registrasi user
POST {{baseurl}}auth/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "coba3348",
  "password": "password123",
  "id_role": 2 
} 

### get all data barang
GET {{baseurl}}barang?page=1&limit=5
Authorization: Bearer {{token}}
Content-Type: application/json


### edit company
PUT {{baseurl}}company/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "address": "Jl. Baru No. 999"
}



### registrasi user
POST {{baseurl}}auth/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "pegawai",
  "password": "password123"
} 











### tambah barang
POST {{baseurl}}barang
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nama": "Laptop Lenovo",
  "harga": 10000000,
  "stok": 15,
  "deskripsi": "Laptop untuk kerja"
}

### get data barang barang
GET {{baseurl}}barang
Authorization: Bearer {{token}}
Content-Type: application/json


### get data barang barang by id
GET {{baseurl}}barang/110
Authorization: Bearer {{token}}
Content-Type: application/json



### edit barang
PUT {{baseurl}}barang/4
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nama": "Laptop yoga",
  "harga": 10000000,
  "stok": 15,
  "deskripsi": "Laptop untuk kerja"
}


### edit barang
DELETE {{baseurl}}barang/2
Authorization: Bearer {{token}}
Content-Type: application/json
 


### get all data barang
GET {{baseurl}}barang?page=1&limit=5
Authorization: Bearer {{token}}
Content-Type: application/json






### get all data menu
GET {{baseurl}}menus
Authorization: Bearer {{token}}
Content-Type: application/json




### get all data by id
GET {{baseurl}}menus/3
Authorization: Bearer {{token}}
Content-Type: application/json



### Tambah menu
POST {{baseurl}}menus
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Settings",
  "url": "/settings",
  "icon": "gearss",
  "order_no": 4,
  "is_active": true,
  "parent": 2
}


### edit menu
PUT {{baseurl}}menus/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Postss",
  "order_no": 2,
  "is_active": false
}
